---
- name: Create Uptime Kuma base directory
  ansible.builtin.file:
    path: "{{ uptime_kuma_directory }}"
    state: directory
    mode: '0755'

- name: Deploy docker-compose configuration
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ uptime_kuma_directory }}/docker-compose.yml"
    mode: '0644'

- name: Start Uptime Kuma using Docker Compose
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: "{{ uptime_kuma_directory }}"
  changed_when: false
